services:
  - type: web
    name: pdf-translator
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT server:app
    autoDeploy: true
